# Generated by Django 5.1.1 on 2024-10-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Student"), (2, "Teacher"), (3, "Admin")], default=3
            ),
        ),
    ]
