# Generated by Django 5.1.1 on 2024-10-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
