[phases.setup]
apt_packages = ["python3", "gcc"]

[phases.install]
commands = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.start]
command = "gunicorn student_management_system.wsgi:application --bind 0.0.0.0:8000"
